package com.cykj.ssh.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer",catalog="ceshi")
public class Customer implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@Column(name = "name",length=50,nullable = false)
	private String name;
	
	@Column(name = "sex")
	private Integer sex;
	
	@Column(name = "birthday")
	private Date birthday;
	
	@Column(name = "height",precision=22,scale=0)
	private Double height;
	
	@Column(name = "weight",precision=22,scale=0)
	private Double weight;

	public Customer() {
	}

	public Customer(String name) {
		this.name = name;
	}

	public Customer(String name, Integer sex, Date birthday, Double height,
			Double weight) {
		this.name = name;
		this.sex = sex;
		this.birthday = birthday;
		this.height = height;
		this.weight = weight;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Double getHeight() {
		return this.height;
	}

	public void setHeight(Double height) {
		this.height = height;
	}

	public Double getWeight() {
		return this.weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

}
