package com.cykj.ssh.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductType generated by hbm2java
 */
@Entity
@Table(name="product_type",catalog="ceshi")
public class ProductType implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "productTypeId", unique = true, nullable = false)
	private Integer productTypeId;
	
	@Column(name = "productTypeName",length=60)
	private String productTypeName;
	
	@Column(name = "parentTypeId")
	private Integer parentTypeId;

	public ProductType() {
	}

	public ProductType(String productTypeName, Integer parentTypeId) {
		this.productTypeName = productTypeName;
		this.parentTypeId = parentTypeId;
	}

	public Integer getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(Integer productTypeId) {
		this.productTypeId = productTypeId;
	}

	public String getProductTypeName() {
		return this.productTypeName;
	}

	public void setProductTypeName(String productTypeName) {
		this.productTypeName = productTypeName;
	}

	public Integer getParentTypeId() {
		return this.parentTypeId;
	}

	public void setParentTypeId(Integer parentTypeId) {
		this.parentTypeId = parentTypeId;
	}

}
