package com.cykj.ssh.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product",catalog="ceshi")
public class Product implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "productId", unique = true, nullable = false)
	private Integer productId;
	
	@Column(name = "productNo", length=30)
	private String productNo;
	
	@Column(name = "productName", length=60)
	private String productName;
	
	@Column(name = "productStatus",nullable=false)
	private int productStatus;
	
	@Column(name = "originalPrice",precision=22,scale=0)
	private Double originalPrice;
	
	@Column(name = "discountPrice",precision=22,scale=0)
	private Double discountPrice;
	
	@Column(name = "productTypeId")
	private Integer productTypeId;

	public Product() {
	}

	public Product(int productStatus) {
		this.productStatus = productStatus;
	}

	public Product(String productNo, String productName, int productStatus,
			Double originalPrice, Double discountPrice, Integer productTypeId) {
		this.productNo = productNo;
		this.productName = productName;
		this.productStatus = productStatus;
		this.originalPrice = originalPrice;
		this.discountPrice = discountPrice;
		this.productTypeId = productTypeId;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public String getProductNo() {
		return this.productNo;
	}

	public void setProductNo(String productNo) {
		this.productNo = productNo;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public int getProductStatus() {
		return this.productStatus;
	}

	public void setProductStatus(int productStatus) {
		this.productStatus = productStatus;
	}

	public Double getOriginalPrice() {
		return this.originalPrice;
	}

	public void setOriginalPrice(Double originalPrice) {
		this.originalPrice = originalPrice;
	}

	public Double getDiscountPrice() {
		return this.discountPrice;
	}

	public void setDiscountPrice(Double discountPrice) {
		this.discountPrice = discountPrice;
	}

	public Integer getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(Integer productTypeId) {
		this.productTypeId = productTypeId;
	}

}
